---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma-lanmine
  namespace: uptime-kuma
  annotations:
    cert-manager.io/cluster-issuer: vault-issuer
    cert-manager.io/common-name: uptime.lanmine.local
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - uptime.lanmine.local
      secretName: uptime-lanmine-tls
  rules:
    - host: uptime.lanmine.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma
                port:
                  number: 3001
