apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - crowdsec.yaml
  - traefik-bouncer.yaml
  - traefik-middleware.yaml
# Note: crowdsec-bouncer-key secret must be created manually from Vault:
# kubectl create secret generic crowdsec-bouncer-key -n crowdsec \
#   --from-literal=api_key=$(vault kv get -field=traefik_bouncer_api_key secret/infrastructure/crowdsec)
