apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: crowdsec-bouncer
  namespace: traefik
spec:
  forwardAuth:
    address: http://crowdsec-traefik-bouncer-service.crowdsec.svc.cluster.local/api/v1/forwardAuth
    trustForwardHeader: true
