apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - notifications
  - infrastructure.yaml
  - metallb-config.yaml
  - cert-manager-config.yaml
  - external-secrets-config.yaml
  - apps.yaml
