apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opnsense-exporter-credentials
  namespace: opnsense-exporter
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: opnsense-exporter-credentials
    creationPolicy: Owner
  data:
    - secretKey: OPNSENSE_API_KEY
      remoteRef:
        key: infrastructure/opnsense
        property: api_key
    - secretKey: OPNSENSE_API_SECRET
      remoteRef:
        key: infrastructure/opnsense
        property: api_secret
    - secretKey: OPNSENSE_API_URL
      remoteRef:
        key: infrastructure/opnsense
        property: api_url
