apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - externalsecret.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor-api.yaml
  - node-exporter-endpoint.yaml
