apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - externalsecret.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor-api.yaml
  - node-exporter-endpoint.yaml
  - servicemonitor-node.yaml
configMapGenerator:
  - name: opnsense-dashboards
    namespace: monitoring
    files:
      - opnsense-overview.json=dashboards/opnsense-overview.json
      - opnsense-system.json=dashboards/opnsense-system.json
    options:
      labels:
        grafana_dashboard: "1"
      disableNameSuffixHash: true
