apiVersion: v1
kind: Service
metadata:
  name: opnsense-exporter
  namespace: opnsense-exporter
  labels:
    app: opnsense-exporter
spec:
  selector:
    app: opnsense-exporter
  ports:
    - port: 8080
      targetPort: 8080
      name: metrics
      protocol: TCP
  type: ClusterIP
