apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opnsense-exporter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Lanmine/lanmine_tech
    targetRevision: main
    path: kubernetes/apps/opnsense-exporter
  destination:
    server: https://kubernetes.default.svc
    namespace: opnsense-exporter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
