apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velero
resources:
  - namespace.yaml
  - externalsecret.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - pdb.yaml
  - backup-storage-location.yaml
  - volume-snapshot-location.yaml
  - schedules.yaml
  - servicemonitor.yaml
