---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: litellm
resources:
  - namespace.yaml
  - externalsecret.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - pdb.yaml
  - servicemonitor.yaml
