---
apiVersion: v1
kind: Service
metadata:
  name: litellm-lb
  namespace: litellm
  labels:
    app: litellm
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.0.10.41"
spec:
  type: LoadBalancer
  selector:
    app: litellm
  ports:
    - port: 4000
      targetPort: 4000
      name: http
      protocol: TCP
