# kubernetes/apps/netbox/ingress-lanmine.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netbox-lanmine
  namespace: netbox
  annotations:
    cert-manager.io/cluster-issuer: vault-issuer
    cert-manager.io/common-name: netbox.lanmine.local
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - netbox.lanmine.local
      secretName: netbox-lanmine-tls
  rules:
    - host: netbox.lanmine.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: netbox
                port:
                  number: 8080
