# kubernetes/apps/netbox/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: netbox-secrets
  namespace: netbox
type: Opaque
stringData:
  secret_key: "PLACEHOLDER"
  db_password: "PLACEHOLDER"
  superuser_password: "PLACEHOLDER"
  superuser_api_token: "PLACEHOLDER"
---
apiVersion: v1
kind: Secret
metadata:
  name: netbox-db-config
  namespace: netbox
type: Opaque
stringData:
  DB_HOST: "10.0.10.23"
  DB_PORT: "5432"
  DB_NAME: "netbox"
  DB_USER: "netbox"
  REDIS_HOST: "netbox-redis"
  REDIS_PORT: "6379"
  REDIS_DATABASE: "0"
  REDIS_CACHE_DATABASE: "1"
