# kubernetes/apps/netbox/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: netbox-postgres
  namespace: netbox
type: Opaque
stringData:
  host: "10.0.10.23"
  port: "5432"
  database: "netbox"
  username: "netbox"
  password: "PLACEHOLDER"
---
apiVersion: v1
kind: Secret
metadata:
  name: netbox-redis
  namespace: netbox
type: Opaque
stringData:
  host: "netbox-redis"
  port: "6379"
  database: "0"
  cache-database: "1"
---
apiVersion: v1
kind: Secret
metadata:
  name: netbox-secret
  namespace: netbox
type: Opaque
stringData:
  secret-key: "PLACEHOLDER"
---
apiVersion: v1
kind: Secret
metadata:
  name: netbox-superuser
  namespace: netbox
type: Opaque
stringData:
  username: "admin"
  email: "admin@lanmine.no"
  password: "PLACEHOLDER"
  api-token: "PLACEHOLDER"
