---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-lanmine
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: vault-issuer
    cert-manager.io/common-name: prometheus.lanmine.local
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - prometheus.lanmine.local
      secretName: prometheus-lanmine-tls
  rules:
    - host: prometheus.lanmine.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kube-prometheus-stack-prometheus
                port:
                  number: 9090
