apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbox
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Lanmine/lanmine_tech
    targetRevision: HEAD
    path: kubernetes/apps/netbox
  destination:
    server: https://kubernetes.default.svc
    namespace: netbox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: netbox-secret
      jsonPointers:
        - /data/secret-key
    - group: ""
      kind: Secret
      name: netbox-postgres
      jsonPointers:
        - /data/password
    - group: ""
      kind: Secret
      name: netbox-superuser
      jsonPointers:
        - /data/password
        - /data/api-token
