apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oxidized
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Lanmine/lanmine_tech
    targetRevision: HEAD
    path: kubernetes/apps/oxidized
  destination:
    server: https://kubernetes.default.svc
    namespace: oxidized
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
