apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oxidized-cloudflare
  namespace: oxidized
  annotations:
    external-dns.alpha.kubernetes.io/hostname: oxidized.hl0.dev
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - oxidized.hl0.dev
      secretName: oxidized-hl0-tls
  rules:
    - host: oxidized.hl0.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oxidized
                port:
                  number: 8888
