apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oxidized-tailscale
  namespace: oxidized
  annotations:
    tailscale.com/funnel: "false"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: oxidized
      port:
        number: 8888
  tls:
    - hosts:
        - oxidized
