apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium
  - kube-system
  - storage
  - metallb
  - cert-manager
  - external-secrets
  - external-dns
  - tailscale
  - ingress
  - monitoring
  - crowdsec
  - network-policies
  - snmp-exporter
