---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-cloudflare
  namespace: argocd
  annotations:
    external-dns.alpha.kubernetes.io/hostname: argocd.hl0.dev
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: argocd-stripprefix@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - argocd.hl0.dev
      secretName: argocd-hl0-tls
  rules:
    - host: argocd.hl0.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80
