apiVersion: v1
kind: Service
metadata:
  name: authentik-ldap
  namespace: authentik
  labels:
    app: authentik-ldap
spec:
  type: LoadBalancer
  ports:
  - name: ldap
    port: 389
    targetPort: 3389
    protocol: TCP
  - name: ldaps
    port: 636
    targetPort: 6636
    protocol: TCP
  selector:
    app: authentik-ldap
