apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - kube-prometheus-stack.yaml
  - flux-monitoring.yaml
  - flux-dashboard.yaml
  - network-dashboard.yaml
