apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - grafana-helmrepository.yaml
  - kube-prometheus-stack.yaml
  - loki.yaml
  - loki-external.yaml
  - tempo.yaml
  - alloy.yaml
  - alloy-syslog.yaml
  - flux-monitoring.yaml
  - flux-dashboard.yaml
  - network-dashboard.yaml
  - infrastructure-logs-dashboard.yaml
  - overview-dashboard.yaml
  - blackbox-exporter.yaml
  - infrastructure-alerts.yaml
