apiVersion: v1
kind: Service
metadata:
  name: loki-external
  namespace: monitoring
  annotations:
    metallb.universe.tf/loadBalancerIPs: "10.0.10.49"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: single-binary
  ports:
    - name: http
      port: 3100
      targetPort: 3100
      protocol: TCP
