apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
resources:
  - namespace.yaml
  - pvc.yaml
  - externalsecret.yaml
  - deployment.yaml
  - service.yaml
  - pdb.yaml
  - bucket-init-job.yaml
