apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    server: https://vault-01.lionfish-caiman.ts.net:8200
    path: pki/sign/lanmine-local
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROekNDQWgrZ0F3SUJBZ0lVS0dxWEZsRFkrVjcrUVlaTC9IeCszQ0VsalN3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0l6RWhNQjhHQTFVRUF4TVlUR0Z1YldsdVpTQkpiblJsY201aGJDQlNiMjkwSUVOQk1CNFhEVEkyTURFeQpOREV5TXpBeU0xb1hEVE0yTURFeU1qRXlNekExTTFvd0l6RWhNQjhHQTFVRUF4TVlUR0Z1YldsdVpTQkpiblJsCmNtNWhiQ0JTYjI5MElFTkJNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTFhRjAKY2FqSThoY0NSNWVGYk1YTjgrTXdRcnJjZnlTNHlmMWNQOXlNNkdqYU02L1RKWTYydHM3OE95TndyanZtd3VBOQpYUDkwem5mZStMRkY3T2dsV0hVRG05Q2RHMFo0Q3oyM3V2N0t3dEFrR29DYnc3ZFZKRG5sN001dHRURE16ZUlhCmVxdkFWSXQ4bzdtUStEeCtLcDh2OWl2dENsTERyQUtJL2hTM3ZKS0VpYklreGJsQ0NEOXRSMlhadnVZUGZBSzgKV1ZuNW5vVWxPT1hXL2RMUWRsNVlpcnhTOGVyZTNUd01kbDNjVkU0eVlaWjNwcHk1Zk9mRmM0aW8rcVViV3JwTgpMTzhvV2k1bFUxT3dINHdQRlRKYXNYeXU3bGwxZlpreUpkNk1DS25aTmdLRWkzdkR1VHN1ZkVacGxNcEloUURDCmx1cG1rQUw0bFRzaEc1MDNYd0lEQVFBQm8yTXdZVEFPQmdOVkhROEJBZjhFQkFNQ0FRWXdEd1lEVlIwVEFRSC8KQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVR3pHeWVaMjJqZEpvOU5KYlVnaTN5VVY2QVkwd0h3WURWUjBqQkJndwpGb0FVR3pHeWVaMjJqZEpvOU5KYlVnaTN5VVY2QVkwd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFMcnZuWEhBCnhvTUM4VGlRcHk1ajBpK3NCQi9QMzZvSnhaUTl5TmxZNFJSMytGTXVPYVVTa1Y4Z0I3QVVzeEM2NmZVV2VPUEYKUmkxWmtSbmdmR3ovNE52Um1sNDVlMVJpaDB3aTJXL2MzUlRQK2FLK2VtRUFsRHVMYk1GUEhnSjlpVXBNbmtjagpQVHBsVVFhTkVsd3ZqT0txcVdxdTExUWl1UnlMS2tmUUdzSnF3YkdwZWZ3SUp1c3pONlk0TXRwZmY3RDR3MldICkh3NnNldTlLRDNERE42YUdxbDVzSlZGRFlGVHFna2s0SS9EWWplOUtTU1FpOWJzNTZLTFQySjFKRWJ2UDM3TFUKQUJKTC9LRDJVaXR0NVl3cWJLMytvSjBHT082ejRXUWVMZTRPTkIwMW5MaXNYdi9GTGlQbTNQbWJiVjdzV1pyOAo3SmpPN3Y5RU93aHhmbWc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    auth:
      appRole:
        path: approle
        roleId: c61ed09d-43d8-7614-1456-b7c781c88723
        secretRef:
          name: vault-approle
          key: secretId
