apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    server: https://vault-01.lionfish-caiman.ts.net:8200
    path: pki/sign/lanmine-local
    auth:
      appRole:
        path: approle
        roleId: c61ed09d-43d8-7614-1456-b7c781c88723
        secretRef:
          name: vault-approle
          key: secretId
