---
apiVersion: v1
kind: Service
metadata:
  name: vault-external
  namespace: vault
spec:
  ports:
    - port: 8200
      targetPort: 8200
      protocol: TCP
      name: https
---
apiVersion: v1
kind: Endpoints
metadata:
  name: vault-external
  namespace: vault
subsets:
  - addresses:
      - ip: 10.0.10.21
    ports:
      - port: 8200
        name: http
