apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glance-tailscale
  namespace: glance
  annotations:
    tailscale.com/funnel: "false"
    tailscale.com/hostname: "glance"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: glance
      port:
        number: 8080
  tls:
    - hosts:
        - glance
