title: Lanmine Infrastructure
description: A living blog documenting the daily life of homelab infrastructure
url: "https://lanmine.github.io/lanmine_tech"

remote_theme: jekyll/minima
markdown: kramdown

minima:
  skin: dark

# Blog settings
permalink: /:year/:month/:day/:title/
show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
