---
# External service pointing to Akvorado VM
apiVersion: v1
kind: Service
metadata:
  name: akvorado-external
  namespace: default
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
# Endpoints for the external service
apiVersion: v1
kind: Endpoints
metadata:
  name: akvorado-external
  namespace: default
subsets:
  - addresses:
      - ip: 10.0.10.26
    ports:
      - port: 8080
        protocol: TCP
---
# Tailscale ingress for HTTPS access
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: akvorado-tailscale
  namespace: default
  annotations:
    tailscale.com/funnel: "false"
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: akvorado-external
      port:
        number: 8080
  tls:
    - hosts:
        - akvorado
